function run_model_sims!(nsims,tmax,x0,par)
        let        
        for j=1:nsims
            global x = dengue_2st!(x0,par,2)  
            global newcases_all_h = vcat(x0[2],x[2])
            global newcases_all_m = vcat(x0[3],x[3])
            global hpop = vcat(x0[4],x[4])
            global mpop = vcat(x0[5],x[5])
            global lpop = vcat(x0[17],x[17])
            global hbirths = vcat(x0[6],x[6])
            global hdeaths = vcat(x0[7],x[7])
            global lambda_h1 = vcat(x0[8],(x[8]))
            global lambda_h2 = vcat(x0[9],(x[9]))
            global lambda_m1 = vcat(x0[10],(x[10]))
            global lambda_m2 = vcat(x0[11],(x[11]))
            global S0dt = vcat(0,(x[1][1]))
            global E1dt = vcat(0,(x[1][2]))
            global E2dt = vcat(0,(x[1][3]))
            global I1dt = vcat(0,(x[1][4]))
            global I2dt = vcat(0,(x[1][5]))
            global R1dt = vcat(0,(x[1][6]))
            global R2dt = vcat(0,(x[1][7]))
            global S1dt = vcat(0,(x[1][8]))
            global S2dt = vcat(0,(x[1][9]))
            global E12dt = vcat(0,(x[1][10]))
            global E21dt = vcat(0,(x[1][11]))
            global I12dt = vcat(0,(x[1][12]))
            global I21dt = vcat(0,(x[1][13]))
            global R12dt = vcat(0,(x[1][14]))
            global R21dt = vcat(0,(x[1][15]))
            global Lmdt = vcat(0,(x[1][16]))
            global Smdt = vcat(0,(x[1][17]))
            global E1mdt = vcat(0,(x[1][18]))
            global E2mdt = vcat(0,(x[1][19]))
            global I1mdt = vcat(0,(x[1][20]))
            global I2mdt = vcat(0,(x[1][21]))
            global newcases_st1_h = vcat(x0[18],x[18])
            global newcases_st2_h = vcat(x0[19],x[19])
                

                for i in 3:tmax
                    x = dengue_2st!(x,par,i);
                    newcases_all_h = vcat(newcases_all_h,x[2])
                    newcases_all_m = vcat(newcases_all_m,x[3])
                    hpop = vcat(hpop,x[4])
                    mpop = vcat(mpop,x[5])
                    lpop = vcat(lpop,x[17])
                    hbirths = vcat(hbirths,x[6])
                    hdeaths = vcat(hdeaths,x[7])
                    lambda_h1 = vcat(lambda_h1,(x[8]))
                    lambda_h2 = vcat(lambda_h2,(x[9]))
                    lambda_m1 = vcat(lambda_m1,(x[10]))
                    lambda_m2 = vcat(lambda_m2,(x[11]))
                    S0dt = vcat(S0dt,(x[1][1]))
                    E1dt = vcat(E1dt,(x[1][2]))
                    E2dt = vcat(E2dt,(x[1][3]))
                    I1dt = vcat(I1dt,(x[1][4]))
                    I2dt = vcat(I2dt,(x[1][5]))
                    R1dt = vcat(R1dt,(x[1][6]))
                    R2dt = vcat(R2dt,(x[1][7]))
                    S1dt = vcat(S1dt,(x[1][8]))
                    S2dt = vcat(S2dt,(x[1][9]))
                    E12dt = vcat(E12dt,(x[1][10]))
                    E21dt = vcat(E21dt,(x[1][11]))
                    I12dt = vcat(I12dt,(x[1][12]))
                    I21dt = vcat(I21dt,(x[1][13]))
                    R12dt = vcat(R12dt,(x[1][14]))
                    R21dt = vcat(R21dt,(x[1][15]))
                    Lmdt = vcat(Lmdt,(x[1][16]))
                    Smdt = vcat(Smdt,(x[1][17]))
                    E1mdt = vcat(E1mdt,(x[1][18]))
                    E2mdt = vcat(E2mdt,(x[1][19]))
                    I1mdt = vcat(I1mdt,(x[1][20]))
                    I2mdt = vcat(I2mdt,(x[1][21]))
                    newcases_st1_h = vcat(newcases_st1_h,x[18])
                    newcases_st2_h = vcat(newcases_st2_h,x[19])
                end
        end
        
        return[newcases_all_h,newcases_all_m,newcases_st1_h,newcases_st2_h,
        hpop,mpop,lpop,hbirths,hdeaths,
        lambda_h1,lambda_h2,lambda_m1,lambda_m2,
        S0dt,E1dt,E2dt,I1dt,I2dt,R1dt,R2dt,S1dt,S2dt,E12dt,E21dt,I12dt,I21dt,R12dt,R21dt,
        Lmdt,Smdt,E1mdt,E2mdt,I1mdt,I2mdt]
        end
end