using Random,Distributions,DataFrames,LinearAlgebra,CSV,JLD2,Dates

@time begin
        for j=1:nsims
            x = dengue_sde_2st!(x0,par,m,2)  
            newcases_all_h = vcat(x0[2],x[2])
            newcases_all_m = vcat(x0[3],x[3])
            hpop = vcat(x0[4],x[4])
            mpop = vcat(x0[5],x[5])
            lpop = vcat(x0[17],x[17])
            hbirths = vcat(x0[6],x[6])
            hdeaths = vcat(x0[7],x[7])
            λh1 = vcat(x0[8],(x[8]))
            λh2 = vcat(x0[9],(x[9]))
            λm1 = vcat(x0[10],(x[10]))
            λm2 = vcat(x0[11],(x[11]))
            S0dt = vcat(0,(x[1][1]))
            E1dt = vcat(0,(x[1][2]))
            E2dt = vcat(0,(x[1][3]))
            I1dt = vcat(0,(x[1][4]))
            I2dt = vcat(0,(x[1][5]))
            R1dt = vcat(0,(x[1][6]))
            R2dt = vcat(0,(x[1][7]))
            S1dt = vcat(0,(x[1][8]))
            S2dt = vcat(0,(x[1][9]))
            E12dt = vcat(0,(x[1][10]))
            E21dt = vcat(0,(x[1][11]))
            I12dt = vcat(0,(x[1][12]))
            I21dt = vcat(0,(x[1][13]))
            R12dt = vcat(0,(x[1][14]))
            R21dt = vcat(0,(x[1][15]))
            Lmdt = vcat(0,(x[1][16]))
            Smdt = vcat(0,(x[1][17]))
            E1mdt = vcat(0,(x[1][18]))
            E2mdt = vcat(0,(x[1][19]))
            I1mdt = vcat(0,(x[1][20]))
            I2mdt = vcat(0,(x[1][21]))
            newcases_st1_h = vcat(x0[18],x[18])
            newcases_st2_h = vcat(x0[19],x[19])
                

                for i in 3:tmax
                    x = dengue_sde_2st!(x,par,m,i);
                    newcases_all_h = vcat(newcases_all_h,x[2])
                    newcases_all_m = vcat(newcases_all_m,x[3])
                    hpop = vcat(hpop,x[4])
                    mpop = vcat(mpop,x[5])
                    lpop = vcat(lpop,x[17])
                    hbirths = vcat(hbirths,x[6])
                    hdeaths = vcat(hdeaths,x[7])
                    λh1 = vcat(λh1,(x[8]))
                    λh2 = vcat(λh2,(x[9]))
                    λm1 = vcat(λm1,(x[10]))
                    λm2 = vcat(λm2,(x[11]))
                    S0dt = vcat(S0dt,(x[1][1]))
                    E1dt = vcat(E1dt,(x[1][2]))
                    E2dt = vcat(E2dt,(x[1][3]))
                    I1dt = vcat(I1dt,(x[1][4]))
                    I2dt = vcat(I2dt,(x[1][5]))
                    R1dt = vcat(R1dt,(x[1][6]))
                    R2dt = vcat(R2dt,(x[1][7]))
                    S1dt = vcat(S1dt,(x[1][8]))
                    S2dt = vcat(S2dt,(x[1][9]))
                    E12dt = vcat(E12dt,(x[1][10]))
                    E21dt = vcat(E21dt,(x[1][11]))
                    I12dt = vcat(I12dt,(x[1][12]))
                    I21dt = vcat(I21dt,(x[1][13]))
                    R12dt = vcat(R12dt,(x[1][14]))
                    R21dt = vcat(R21dt,(x[1][15]))
                    Lmdt = vcat(Lmdt,(x[1][16]))
                    Smdt = vcat(Smdt,(x[1][17]))
                    E1mdt = vcat(E1mdt,(x[1][18]))
                    E2mdt = vcat(E2mdt,(x[1][19]))
                    I1mdt = vcat(I1mdt,(x[1][20]))
                    I2mdt = vcat(I2mdt,(x[1][21]))
                    newcases_st1_h = vcat(newcases_st1_h,x[18])
                    newcases_st2_h = vcat(newcases_st2_h,x[19])
                end
        
        CSV.write(string("output_data/testsim_",intv,"_FOIh1_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(λh1), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_FOIm1_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(λm1), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_FOIh2_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(λh2), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_FOIm2_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(λm2), writeheader=true)
        
        CSV.write(string("output_data/testsim_",intv,"_newcases_st1_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(newcases_st1_h), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_newcases_st2_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(newcases_st2_h), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_newcases_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(newcases_all_h), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_newcasesM_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(newcases_all_m), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_hpop_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(hpop), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_mpop_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(mpop), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_lpop_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(lpop), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_hbirths_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(hbirths), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_hdeaths_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(hdeaths), writeheader=true)
        
        CSV.write(string("output_data/testsim_",intv,"_S0h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(S0dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_E1h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(E1dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_E2h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(E2dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_I1h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(I1dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_I2h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(I2dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_R1h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(R1dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_R2h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(R2dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_S1h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(S1dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_S2h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(S2dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_E12h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(E12dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_E21h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(E21dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_I12h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(I12dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_I21h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(I21dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_R12h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(R12dt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_R21h_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(R21dt), writeheader=true)
        
        CSV.write(string("output_data/testsim_",intv,"_Lm_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(Lmdt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_Sm_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(Smdt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_Em1_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(E1mdt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_Im1_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(I1mdt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_Em2_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(E2mdt), writeheader=true)
        CSV.write(string("output_data/testsim_",intv,"_Im2_",Dates.today(),"_R0",round(R0,digits=2),"_sero2_",j,".csv"), Tables.table(I2mdt), writeheader=true)

        
        end

end